In [2]:
import numpy as np
import pandas as pd
from scipy.optimize import minimize
import yfinance as yf

In [3]:
def gen_portfolio(tickers, start, interval):
    index = pd.Series()
    return_rates = {}
    for tkr in tickers:
        if interval == '1y':
            data = yf.Ticker(tkr).history(start=start, interval='1mo').iloc[::12]
        else:
            data = yf.Ticker(tkr).history(start=start, interval=interval)
        if not data.Close.empty:
            data = data.Close.pct_change().dropna()
            if len(index) > 0 and data.shape[0] < len(index):
                print(f'Skipping ticker {tkr} due to insufficient data')
            else:            
                index = data.index
                return_rates[tkr] = data.to_numpy()
    return pd.DataFrame(return_rates, index=index)

In [4]:
pf_indices = gen_portfolio(['^GSPC', 'AGG', '^SPGSCI'], '2004-01-1', '1y')
pf_tech = gen_portfolio(['AAPL', 'MSFT', 'AMZN'], '2000-01-01', '1y')
pf_large = gen_portfolio(['MSFT', 'AAPL', 'AMZN',
                          'BRK-A', 'JPM', 'WMT', 'JNJ',
                          'LLY', 'XOM', 'PG', 'LIN', 'GE', 
                          'SAP', 'NEE', 'PLD', 'COKE'], 
                          '2000-01-01', '1y')
pf_sp_500 = gen_portfolio(pd.read_csv('../data/sp500_members.csv').Symbol, '2010-01-01', '1y')

Skipping ticker ABBV due to insufficient data
Skipping ticker ABNB due to insufficient data
Skipping ticker ALLE due to insufficient data
Skipping ticker AMCR due to insufficient data
Skipping ticker APTV due to insufficient data
Skipping ticker ANET due to insufficient data
Skipping ticker CZR due to insufficient data
Skipping ticker CARR due to insufficient data
Skipping ticker CTLT due to insufficient data
Skipping ticker CBOE due to insufficient data
Skipping ticker CDW due to insufficient data
Skipping ticker CFG due to insufficient data
Skipping ticker CEG due to insufficient data
Skipping ticker CTVA due to insufficient data
Skipping ticker DAY due to insufficient data
Skipping ticker FANG due to insufficient data
Skipping ticker DOW due to insufficient data
Skipping ticker ENPH due to insufficient data
Skipping ticker EPAM due to insufficient data
Skipping ticker ETSY due to insufficient data
Skipping ticker FLT due to insufficient data
Skipping ticker FTV due to insufficient d

In [21]:
from datetime import date, timedelta
import json
import requests
res = requests.get('https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates?filter=record_date:gt:'+str(date.today()-timedelta(days=30)))
json_data = json.loads(res.content.decode('utf8'))
print(json_data['data'])
RISK_FREE = 0.05

def shrp(return_rates, w):
    R = np.matmul(return_rates.to_numpy(), w)
    return (R.mean()-RISK_FREE)/R.std()

[{'record_date': '2024-02-29', 'security_type_desc': 'Marketable', 'security_desc': 'Treasury Bills', 'avg_interest_rate_amt': '5.384', 'src_line_nbr': '1', 'record_fiscal_year': '2024', 'record_fiscal_quarter': '2', 'record_calendar_year': '2024', 'record_calendar_quarter': '1', 'record_calendar_month': '02', 'record_calendar_day': '29'}, {'record_date': '2024-02-29', 'security_type_desc': 'Marketable', 'security_desc': 'Treasury Notes', 'avg_interest_rate_amt': '2.394', 'src_line_nbr': '2', 'record_fiscal_year': '2024', 'record_fiscal_quarter': '2', 'record_calendar_year': '2024', 'record_calendar_quarter': '1', 'record_calendar_month': '02', 'record_calendar_day': '29'}, {'record_date': '2024-02-29', 'security_type_desc': 'Marketable', 'security_desc': 'Treasury Bonds', 'avg_interest_rate_amt': '3.119', 'src_line_nbr': '3', 'record_fiscal_year': '2024', 'record_fiscal_quarter': '2', 'record_calendar_year': '2024', 'record_calendar_quarter': '1', 'record_calendar_month': '02', 'recor

In [6]:
def numerical_gradient(w, i, h):
    w_new = w.copy()
    w_new[i] = w[i]+h
    return w_new/w_new.sum()

def gradient_ascent(return_rates, interval=1, epochs = 10000, learning_rate = 0.001):
    w = np.array([1/return_rates.shape[1] for _ in range(return_rates.shape[1])])
    h = h = 0.0000001
    max_score = 0
    max_w = []

    for _ in range(epochs):
        grad = np.zeros(len(w))
        for i in range(len(w)):
            w_l = numerical_gradient(w, i, -h)
            w_r = numerical_gradient(w, i, h)
            grad[i] = (shrp(return_rates, w_r)-shrp(return_rates, w_l))/(2*h)
        w += learning_rate*grad
        w /= w.sum()
        w[w < 0] = 0
        w /= w.sum()
        score = shrp(return_rates, w)
        if score > max_score:
            max_w = w
            max_score = score

    print(max_score)
    return max_w

In [7]:
print(gradient_ascent(pf_indices))
print(gradient_ascent(pf_tech))

0.25190443568076165
[1. 0. 0.]
0.6587758997104967
[0.48935508 0.         0.51064492]


In [8]:
def optimize_shrp(return_rates):
    w0 = [1/return_rates.shape[1] for _ in range(return_rates.shape[1])]
    bounds = [(0, 1) for _ in range(len(w0))]
    result = minimize(lambda w: -shrp(return_rates, w), w0, bounds=bounds, constraints={'type': 'eq', 'fun': lambda x: sum(x)-1})
    print(-result.fun)
    return result.x

In [9]:
print(optimize_shrp(pf_indices))
print(optimize_shrp(pf_tech))
print(pd.Series(optimize_shrp(pf_large), index=pf_large.columns).apply(lambda x: 100*x))
sp_500_opt = pd.Series(optimize_shrp(pf_sp_500), index=pf_sp_500.columns)

0.2519044356807616
[1.00000000e+00 1.38777878e-17 2.22044605e-16]
0.6587759198669562
[0.48919667 0.         0.51080333]
1.166854714340244
MSFT     0.000000e+00
AAPL     4.673505e+00
AMZN     7.959023e+00
BRK-A    4.794408e-14
JPM      9.537614e-15
WMT      0.000000e+00
JNJ      2.039312e-14
LLY      1.574903e+01
XOM      8.328057e+00
PG       0.000000e+00
LIN      1.686400e+01
GE       0.000000e+00
SAP      0.000000e+00
NEE      3.539531e+01
PLD      1.873267e-14
COKE     1.103107e+01
dtype: float64
905.8378803896163


In [10]:
R = np.matmul(pf_sp_500, sp_500_opt)
R.describe()

count    14.000000
mean      0.284344
std       0.000268
min       0.283917
25%       0.284126
50%       0.284343
75%       0.284576
max       0.284710
dtype: float64

In [11]:
print(sp_500_opt.sort_values().tail(20))
pf_top_20 = gen_portfolio(sp_500_opt.sort_values().tail(20).index, '2010-01-01', '1y')
R = np.matmul(pf_top_20, sp_500_opt.sort_values().tail(20))
R

FE      0.006905
AMD     0.007906
EQIX    0.007964
BSX     0.008443
VLO     0.008753
FSLR    0.010502
ORLY    0.014259
MCD     0.017909
AMZN    0.019762
MSCI    0.023509
MPWR    0.023687
LLY     0.048704
KDP     0.057252
BLDR    0.062787
DXCM    0.066163
MOH     0.080503
HRL     0.093778
STLD    0.099261
ULTA    0.116633
FICO    0.166918
dtype: float64


Date
2011-01-01 00:00:00-05:00    0.269509
2012-01-01 00:00:00-05:00    0.265787
2013-01-01 00:00:00-05:00    0.269853
2014-01-01 00:00:00-05:00    0.265894
2015-01-01 00:00:00-05:00    0.264323
2016-01-01 00:00:00-05:00    0.282176
2017-01-01 00:00:00-05:00    0.269979
2018-01-01 00:00:00-05:00    0.267588
2019-01-01 00:00:00-05:00    0.273737
2020-01-01 00:00:00-05:00    0.277757
2021-01-01 00:00:00-05:00    0.268886
2022-01-01 00:00:00-05:00    0.262186
2023-01-01 00:00:00-05:00    0.275368
2024-01-01 00:00:00-05:00    0.277799
dtype: float64